Sample\CsvBundle\Entity\Data:
    type: entity
    table: data
    repositoryClass: Sample\CsvBundle\Entity\DataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sourceId:
            type: integer
            column: source_id
        fileId:
            type: integer
            column: file_id
        periodId:
            type: integer
            column: period_id
        topicId:
            type: string
            length: 255
            column: topic_id
        price:
            type: float
            precision: 10
            scale: 2
        headers:
            type: text
        values:
            type: text
        isMultiple:
            type: boolean
            column: is_multiple
        multipleId:
            type: integer
            column: multiple_id
            nullable: true
        isActive:
            type: boolean
            column: is_active
        createdAt:
            type: datetime
            column: created_at
            columnDefinition: TIMESTAMP
            nullable: true
        modifiedAt:
            type: datetime
            column: modified_at
            columnDefinition: TIMESTAMP
            nullable: true
    manyToOne:
        source:
            targetEntity: Sources
            joinColumn:
                name: source_id
                referencedColumnName: id
        file:
            targetEntity: Files
            joinColumn:
                name: file_id
                referencedColumnName: id
        period:
            targetEntity: Periods
            joinColumn:
                name: period_id
                referencedColumnName: id
        multiple:
            targetEntity: Multiple
            joinColumn:
                name: multiple_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ timestamps ]
        preUpdate: [ timestamps ]
