<?php

namespace Sample\CsvBundle\Entity;

use Sample\CsvBundle\Entity\SharedRepository;
use Sample\CsvBundle\Entity\Log;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends SharedRepository
{
    /**
     * Return Log or
     * creat a new one
     *
     * @used
     * - ImportCommand::_log
     * - MultipleController::_log
     * @param integer $logTypeId
     * @param string $process
     * @param string $description
     * @return boolean
     */
    public function log($logTypeId, $process, $description)
    {
        $entityManager = $this->getEntityManager();
        $logType = $entityManager
            ->getRepository('SampleCsvBundle:LogTypes')
            ->find($logTypeId);

        if (!empty($logType)) {

            // New Record
            $record = new Log();
            $record->setLogTypeId($logType->getId());
            $record->setProcess($process);
            $record->setDescription($description);
            $record->setFixed(false);
            $record->setLogType($logType);

            $entityManager->persist($record);
            $entityManager->flush();

        } else {
            return false;
        }

        return true;
    }
}
