<?php

namespace Sample\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ADRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ADRoleRepository extends EntityRepository
{
}
